### ISSUE TITLE
[BUG] "read timed out" and "database is locked" with a fresh container

### ISSUE THREAD

**Issue by robbieh** [graphite-project/docker-graphite-statsd#131]
With a fresh copy of this container, I get a ton of errors. The system logs show periodic "Read timed out" errors. And the frontend fails when I try to log in with "sqlite3.OperationalError: database is locked".

**To Reproduce**
Here is my docker-compose.yaml:

```
version: '3'
services:
    graphite:
        image: graphiteapp/graphite-statsd
        container_name: graphite
        restart: always
        ports:
            - "81:80"
            - "2003:2003"
            - "2004:2004"
            - "8125:8125/udp"
            - "8126:8126"
        volumes:
            - "/var/containers/graphite/storage:/opt/graphite/storage:z"
            - "/var/containers/graphite/log:/var/log:z"
       networks:
            - docker-net

networks:
    docker-net:
```

And then I just `docker-compose up`.

I already had collectd set up so data starts flowing in as soon as I start the container. I can access it through Grafana as well.

**Expected behavior**
I'd expect to be able to log in.

**Environment (please complete the following information):**
- System: `Linux olive 4.19.0-8-amd64 #1 SMP Debian 4.19.98-1 (2020-01-26) x86_64 GNU/Linux`
- Latest image: `graphiteapp/graphite-statsd@sha256:18fbffd024cd540c7a57febfaa38c3dc5513f05db2263300209deb2a8ecd923c`
- I've mounted storage and log as shown in the compose file. I've also tried it without mounting any volumes and I still get the same behavior.
- Docker version: 
```
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b7f0
 Built:             Wed Mar 11 01:25:56 2020
 OS/Arch:           linux/amd64
 Experimental:      false
```

**Additional logs**
From `docker logs` I get some lines showing success (and yes, the data shows up in the web interface). But then I get almost as many that say variations on this:

```
graphite    | 18/04/2020 18:00:16 :: [tagdb] Error tagging stats.timers.view.graphite.account.views.POST.sum_90, stats.timers.view.graphite.account.views.POST.upper_90, stats.timers.view.graphite.account.views.POST.mean_90, stats.timers.view.graphite.account.views.POST.count_90, stats.timers.view.graphite.account.views.loginView.POST.median, stats.timers.view.graphite.account.views.loginView.POST.mean, stats.timers.view.graphite.account.views.loginView.POST.sum_squares, stats.timers.view.graphite.account.views.loginView.POST.sum, stats.timers.view.graphite.account.views.loginView.POST.lower, stats.timers.view.graphite.account.views.loginView.POST.upper, stats.timers.view.graphite.account.views.loginView.POST.std, stats.timers.view.graphite.account.views.loginView.POST.sum_squares_90, stats.timers.view.graphite.account.views.loginView.POST.sum_90, stats.timers.view.graphite.account.views.loginView.POST.upper_90, stats.timers.view.graphite.account.views.loginView.POST.mean_90, stats.timers.view.graphite.account.views.loginView.POST.count_90, stats_counts.response.302, collectd.mezcal.irq.irq-124, collectd.mezcal.disk-loop0.disk_octets.write, collectd.Vermouth.users.users: Error requesting http://127.0.0.1:8080/tags/tagMultiSeries: HTTPConnectionPool(host='127.0.0.1', port=8080): Read timed out. (read timeout=5)
```

When I try to log in as `root/root` I get a nasty stack trace:

```
Traceback (most recent call last):
  File "/opt/graphite/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/opt/graphite/lib/python3.8/site-packages/django/db/backends/sqlite3/base.py", line 383, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: database is locked

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/graphite/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/opt/graphite/lib/python3.8/site-packages/django/utils/deprecation.py", line 96, in __call__
    response = self.process_response(request, response)
  File "/opt/graphite/lib/python3.8/site-packages/django_statsd/middleware.py", line 28, in process_response
    if hasattr(request, 'user') and is_authenticated(request.user):
  File "/opt/graphite/lib/python3.8/site-packages/django_statsd/middleware.py", line 21, in is_authenticated
    return user.is_authenticated
  File "/opt/graphite/lib/python3.8/site-packages/django/utils/functional.py", line 256, in inner
    self._setup()
  File "/opt/graphite/lib/python3.8/site-packages/django/utils/functional.py", line 392, in _setup
    self._wrapped = self._setupfunc()
  File "/opt/graphite/lib/python3.8/site-packages/django/contrib/auth/middleware.py", line 24, in <lambda>
    request.user = SimpleLazyObject(lambda: get_user(request))
  File "/opt/graphite/lib/python3.8/site-packages/django/contrib/auth/middleware.py", line 12, in get_user
    request._cached_user = auth.get_user(request)
  File "/opt/graphite/lib/python3.8/site-packages/django/contrib/auth/__init__.py", line 189, in get_user
    user = backend.get_user(user_id)
  File "/opt/graphite/lib/python3.8/site-packages/django/contrib/auth/backends.py", line 102, in get_user
    user = UserModel._default_manager.get(pk=user_id)
  File "/opt/graphite/lib/python3.8/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/opt/graphite/lib/python3.8/site-packages/django/db/models/query.py", line 402, in get
    num = len(clone)
  File "/opt/graphite/lib/python3.8/site-packages/django/db/models/query.py", line 256, in __len__
    self._fetch_all()
  File "/opt/graphite/lib/python3.8/site-packages/django/db/models/query.py", line 1242, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/opt/graphite/lib/python3.8/site-packages/django/db/models/query.py", line 55, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/opt/graphite/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1140, in execute_sql
    cursor.execute(sql, params)
  File "/opt/graphite/lib/python3.8/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/opt/graphite/lib/python3.8/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/opt/graphite/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/opt/graphite/lib/python3.8/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/opt/graphite/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/opt/graphite/lib/python3.8/site-packages/django/db/backends/sqlite3/base.py", line 383, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: database is locked
```

Gunicorn seems to start up OK:
```
[2020-04-18 17:44:40 +0000] [56] [INFO] Starting gunicorn 20.0.4
[2020-04-18 17:44:40 +0000] [56] [INFO] Listening at: http://0.0.0.0:8080 (56)
[2020-04-18 17:44:40 +0000] [56] [INFO] Using worker: sync
[2020-04-18 17:44:40 +0000] [163] [INFO] Booting worker with pid: 163
[2020-04-18 17:44:40 +0000] [164] [INFO] Booting worker with pid: 164
[2020-04-18 17:44:40 +0000] [165] [INFO] Booting worker with pid: 165
[2020-04-18 17:44:41 +0000] [166] [INFO] Booting worker with pid: 166
```

**Comment by deniszh** [comment]
Graphite coming with tagging enabled (same default as in graphite repo), and also - by default - all metrics, which even have no tags are updating in tags database. 
Again, by default, default database is sqlite, and, unfortunately, it's nor disegned nor targeted for production usage. That's why under significant load it's causing locking and database access issues.
So, solution is quite straightforward:
1) if you are using tags (or have plans to do so) - then you need to switch to Redis as tagging engine. You can simply do so using 'REDIS_TAGDB' environment variable - set it to '1'.
```
...
environment:
 - REDIS_TAGDB=1
```
2) if you are not using tags and have no plans to use them - then you can simply disable tagging. Unfortunately, tagging should be disabled in `carbon.conf` file (using `ENABLE_TAGS = False`), which didn't support override through environment variables. (I'll open issue for enabling this feature). So, you need or edit file directly in container or use volume to mount `/opt/graphite/conf` directory and put altered config there.
For now, p.1 is a simplest solution.

**Comment by deniszh** [comment]
Related issues -
https://github.com/graphite-project/carbon/issues/816
https://github.com/graphite-project/carbon/issues/836

**Comment by deniszh** [comment]
Issue for disabling tagging through env variable - https://github.com/graphite-project/docker-graphite-statsd/issues/132

**Comment by robbieh** [comment]
Wow that is amazing. Enabling Redis worked perfectly. There are no more errors in the log, and I was able to log in, update passwd, etc.

Thank you!
