### ISSUE TITLE
It seems i django database has lost 

### ISSUE THREAD

**Issue by lujianmei** [graphite-project/docker-graphite-statsd#18]
Dear,
I have been following the readme to startup a instance, but got error when i access localhost: :

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/graphite/webapp/graphite/composer/views.py", line 35, in composer
    profile = getProfile(request)
  File "/opt/graphite/webapp/graphite/user_util.py", line 25, in getProfile
    return default_profile()
  File "/opt/graphite/webapp/graphite/user_util.py", line 41, in default_profile
    'password': '!'})
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 405, in get_or_create
    return self.get(**lookup), False
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 328, in get
    num = len(clone)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 144, in __len__
    self._fetch_all()
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 965, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 238, in iterator
    results = compiler.execute_sql()
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 840, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/utils.py", line 98, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/sqlite3/base.py", line 318, in execute
    return Database.Cursor.execute(self, query, params)
OperationalError: no such table: auth_user

My configuration is:

statsd:
    container_name: graphite
    image: graphiteapp/graphite-statsd
    ports:
      - "8088:80"
      - "2003-2004:2003-2004"
      - "2023-2024:2023-2024"
      - "8125:8125/udp"
      - "8126:8126"
    volumes:
      - "/Users/kevin/bigdata/graphite/conf:/opt/graphite/conf"
      - "/Users/kevin/bigdata/graphite/storage:/opt/graphite/storage"
      - "/Users/kevin/bigdata/graphite/log:/var/log"
      - "/Users/kevin/bigdata/graphite/log:/var/graphite-log"
      - "/Users/kevin/bigdata/graphite/log:/opt/statsd"
      - "/Users/kevin/bigdata/graphite/logrotate.d:/etc/logrotate.d"

And i found "graphite.db" file under graphite/storage is zerobyte, seems the database initialized failure.

**Comment by deniszh** [comment]
Hi @lujianmei ,
sorry, could you please elaborate your issue in more details? I just in case tried latest graphite image and it works fine.  `graphite.db` is there and everything is working.

**Comment by deniszh** [comment]
If you still have this issue, @lujianmei - please reopen issue.

**Comment by sarahbx** [comment]
Hi @deniszh and @lujianmei. On `v1.1.1` I found when the storage and log volumes are mounted on the host, two additional commands need to be run prior to gunicorn starting.

- The `/var/log/graphite` directory needs to be created
- `/etc/graphite-statsd/conf/usr/local/bin/manage.sh` needs to be run to migrate the db

As a quick fix, I added those commands in `graphite/run`, though I'm sure there's a more logical place for them.
https://github.com/graphite-project/docker-graphite-statsd/blob/v1.1.1/conf/etc/service/graphite/run

Hope this helps :)

**Comment by deniszh** [comment]
@lujianmei : please check now, issue should be fixed
@sarahbx : thanks for your report! I fixed issues and released a new version.

**Comment by sarahbx** [comment]
Thank you @deniszh . I just bumped to the new `-3` version. fyi, I also had to restart the container after giving it some time to init before any data would show up, but I have not tracked down the cause.
