### ISSUE TITLE
[BUG] Issue after moving from 1.1.9 to 1.1.10 docker image

### ISSUE THREAD

**Issue by nneul** [graphite-project/docker-graphite-statsd#210]
**Please open bug only for Docker component here, if you want to do so for Graphite, please use [graphite-web repo](https://github.com/graphite-project/graphite-web/issues/new/choose)**

**Describe the bug**
Getting log message dumps complaining about MIDDLEWARE being undefined with any 1.1.10 or latest image. 

**To Reproduce**
Launch working container with 1.1.9, update to 1.1.10

**Expected behavior**
No errors in logs.

**Environment (please complete the following information):**
 - OS flavor: Ubuntu 20 with Docker-CE
 - Image version: 1.1.9 works, 1.1.10+ does not
 - Custom volumes mounted: relatively vanilla config with just minor tuning, matches container content almost exactly
 - 
 - [e.g. None, /opt/graphite/conf, /opt/graphite/storage etc]

**Additional context**

```
08/07/2022 18:02:25 :: [listener] MetricLineReceiver connection with x.x.x.x:2438 established
08/07/2022 18:02:25 :: [listener] MetricLineReceiver connection with x.x.x.x:24594 established
08/07/2022 18:02:25 :: [listener] MetricLineReceiver connection with x.x.x.x:33486 established
08/07/2022 18:02:25 :: [listener] MetricLineReceiver connection with x.x.x.x:38234 established
08/07/2022 18:02:25 :: [listener] MetricLineReceiver connection with x.x.x.x:43550 established
08/07/2022 18:02:25 :: [listener] MetricLineReceiver connection with x.x.x.x:34070 established
Traceback (most recent call last):
  File "/opt/graphite/bin/django-admin.py", line 5, in <module>
    management.execute_from_command_line()
  File "/opt/graphite/lib/python3.9/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/opt/graphite/lib/python3.9/site-packages/django/core/management/__init__.py", line 325, in execute
    settings.INSTALLED_APPS
  File "/opt/graphite/lib/python3.9/site-packages/django/conf/__init__.py", line 79, in __getattr__
    self._setup(name)
  File "/opt/graphite/lib/python3.9/site-packages/django/conf/__init__.py", line 66, in _setup
    self._wrapped = Settings(settings_module)
  File "/opt/graphite/lib/python3.9/site-packages/django/conf/__init__.py", line 157, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/opt/graphite/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/graphite/webapp/graphite/settings.py", line 238, in <module>
    globals().update(import_module(SETTINGS_MODULE).__dict__)
  File "/opt/graphite/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/graphite/webapp/graphite/local_settings.py", line 451, in <module>
    ) + MIDDLEWARE
NameError: name 'MIDDLEWARE' is not defined
08/07/2022 18:02:25 :: [listener] MetricLineReceiver connection with x.x.x.x:57156 established
08/07/2022 18:02:25 :: [listener] MetricLineReceiver connection with x.x.x.x:47122 established
08/07/2022 18:02:25 :: [listener] MetricLineReceiver connection with x.x.x.x:45480 established
08/07/2022 18:02:25 :: [listener] MetricLineReceiver connection with x.x.x.x:50664 established
```

**Comment by deniszh** [comment]
Fixed in 1.1.10-3, will be built soon.
