### ISSUE TITLE
1.1.5-9 will not start in Docker ([Errno 95] fallocate)

### ISSUE THREAD

**Issue by JerryCurl** [graphite-project/docker-graphite-statsd#93]
26/02/2019 22:35:57 :: [console] Error creating `<any metric i pass it>`: [Errno 95] fallocate
26/02/2019 22:35:57 :: [console] Unhandled Error
Traceback (most recent call last):
  File "/opt/graphite/lib/python3.6/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "/opt/graphite/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/opt/graphite/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
  File "/opt/graphite/lib/carbon/writer.py", line 189, in writeForever
    writeCachedDataPoints()
--- <exception caught here> ---
  File "/opt/graphite/lib/carbon/writer.py", line 142, in writeCachedDataPoints
    state.database.create(metric, archiveConfig, xFilesFactor, aggregationMethod)
  File "/opt/graphite/lib/carbon/database.py", line 145, in create
    self.sparse_create, self.fallocate_create)
  File "/opt/graphite/lib/python3.6/site-packages/whisper.py", line 528, in create
    fallocate(fh, headerSize, remaining)
  File "/opt/graphite/lib/python3.6/site-packages/whisper.py", line 93, in _py_fallocate
    raise IOError(res, 'fallocate')
builtins.OSError: [Errno 95] fallocate

**Comment by deniszh** [comment]
What’s your docker version, host is and host file system are?
Before it was happening only on zfs (it doesn’t support fallocate), maybe
we should disable it by default or fix auto detection in the code.
You can disable fallocate with WHISPER_FALLOCATE=False in carbon.conf

**Comment by JerryCurl** [comment]
Docker 180902, Ubuntu 16.04, and the storage dir is NFS mounted persistent
volume (NetApp AFF)

i disabled fallocate and it is running fine
